# Generated by Django 5.2.1 on 2025-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('shp', 'Shapefile'), ('kml', 'KML'), ('geojson', 'GeoJSON'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crs', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
