# Generated by Django 5.2.1 on 2025-05-13 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakDetectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
                ('threshold', models.FloatField(default=0.0)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
