# Generated by Django 5.2.1 on 2025-05-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0004_mergeddrivingline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergeddrivingline',
            name='name',
            field=models.CharField(default='Merged Drive', max_length=200),
        ),
        migrations.CreateModel(
            name='LeakReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leak_count', models.IntegerField()),
                ('total_leak_value', models.FloatField()),
                ('first_detected', models.DateTimeField()),
                ('last_detected', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapi.pipenetwork')),
            ],
        ),
    ]
