# Generated by Django 5.2.1 on 2025-05-13 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0005_alter_mergeddrivingline_name_leakreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakdetectionpoint',
            name='pipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leak_points', to='geoapi.pipenetwork'),
        ),
    ]
